mappings:
  GridFieldHasOneRelationHandler: Firesphere\GridFieldRelationHandler\GridFieldHasOneRelationHandler
  GridFieldRelationHandler: Firesphere\GridFieldRelationHandler\GridFieldRelationHandler
  GridFieldManyRelationHandler: Firesphere\GridFieldRelationHandler\GridFieldManyRelationHandler
  GridFieldManyRelationHandler_HasManyList: Firesphere\GridFieldRelationHandler\GridFieldManyRelationHandlerHasManyList
  GridFieldManyRelationHandler_ManyManyList: Firesphere\GridFieldRelationHandler\GridFieldManyRelationHandlerManyManyList
